# Generated by Django 3.2.7 on 2021-09-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='DOB',
            new_name='dob',
        ),
    ]
